Import("env")
Import("conf")
Import("objs")

if conf["LIB_PLUMCORE_LOG"] == "y":

	env.Component()

	objs.append(env.Object([
		File(Glob(env['LIB_DEFAULT_REPO_DIR'] + '*.c')),
	]))
	
	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR']),
	])
