Import("env")
Import("conf")
Import("objs")

if conf["LIB_TREECLI"] == "y":

	env.Git('https://github.com/iqyx/treecli', branch='develop')

	objs.append(env.Object([
		File(Glob("src/*.c")),
	]))
	
	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR']),
	])
