Import("env")
Import("conf")
Import("objs")

LOCM3_TARGETS = {
	'stm32g4': 'lib/stm32/g4',
	'stm32h7': 'lib/stm32/h4',
	'stm32u5': 'lib/stm32/u5',
}

if conf["LIB_LIBOPENCM3"] == "y":

	env.Git('https://github.com/libopencm3/libopencm3', branch='master')
	env.Patch([
		'add-stm32-g4-rtc-iwdg.patch',
		'stm32-fix-quadspi.patch',
	])
	env.Make(LOCM3_TARGETS[conf['MCU_FAMILY']], cwd=Dir(env['LIB_DEFAULT_REPO_DIR']))

	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/include'),
	])

	env.Append(LIBPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/lib'),
	])
