#ifndef _HAL_INTERFACE_TYPES_H_
#define _HAL_INTERFACE_TYPES_H_

enum hal_interface_type {
	HAL_INTERFACE_TYPE_NONE = 0,
	HAL_INTERFACE_TYPE_LED,
	HAL_INTERFACE_TYPE_STREAM,
	HAL_INTERFACE_TYPE_SPIBUS,
	HAL_INTERFACE_TYPE_SPIDEV,
	HAL_INTERFACE_TYPE_NETDEV,
	HAL_INTERFACE_TYPE_MACDEV,
	HAL_INTERFACE_TYPE_FLASH,
	HAL_INTERFACE_TYPE_RTC,
	HAL_INTERFACE_TYPE_MAC,
	HAL_INTERFACE_TYPE_RNG,
	HAL_INTERFACE_TYPE_PROFILING,
	HAL_INTERFACE_TYPE_POWER,
	HAL_INTERFACE_TYPE_SENSOR,
	HAL_INTERFACE_TYPE_ADC
};

#endif
