Import("env")
Import("conf")
Import("objs")

objs.append(env.Object(source = [
	File("port.c"),
]))

# target and architecture specific configuration
env.Replace(LDSCRIPT = File("g473cbt6.ld"))
env.Replace(LIBOCM3 = "opencm3_stm32g4")
env.Replace(OOCD_INTERFACE = "stlink")
env.Replace(OOCD_TARGET = "stm32g4x")

env.Append(CFLAGS = [
	"-DSTM32G4",
])

env.Append(CPPPATH = [Dir(".")])

env.Append(LINKFLAGS = [
	"-Wl,-u_printf_float",
])
