Import("env")
Import("conf")
Import("objs")

if conf["LIB_LITTLEFS"] == "y":

	env.Git('https://github.com/littlefs-project/littlefs', branch='v2.8.2')

	objs.append(env.Object([
		File(env['LIB_DEFAULT_REPO_DIR'] + '/lfs.c'),
	]))
	
	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR']),
	])
