import os

Import("env")
Import("conf")
Import("objs")

app_ext_dir = None
if conf["APP_EXTERNAL"] == "y":
	try:
		app_ext_dir = os.environ["PLUMCORE_EXT_APP"]
	except KeyError:
		raise Exception("Env variable with external application path not defined (%s)" % app_ext_dir_var)

	if not os.path.exists(app_ext_dir):
		raise Exception("External application directory cannot be found")

	print("Including external application in '%s'" % app_ext_dir)

	# try:
		# env.LoadKconfig(app_ext_dir + "/Kconfig", app_ext_dir + "/.config")
	# except:
		# raise Exception("Cannot import external application configuration. Did you run menuconfig?")

# Configuration of the external application is loaded now (if selected). Continue as usual

app_name = conf.get("APP_NAME")
if not app_name:
	raise Exception("Application name not defined. Check the corresponding section in Kconfig")

if app_ext_dir:
	SConscript(app_ext_dir + "/SConscript")
else:
	SConscript(app_name + "/SConscript")
