Import("env")
Import("objs")
Import("conf")

if conf["SERVICE_CLI"] == "y":
	objs.append(env.Object([
		File("system_cli_tree.c"),
		File("config_export.c"),
		File("cli.c"),
		File("cli_table_helper.c"),
		File("cli_progressbar_helper.c"),
		File("system_debug.c"),
		File("fs.c"),
		File("device_lora.c"),
	]))
	if conf["SERVICE_UXB_MASTER"] == "y":
		objs.append(env.Object(File("device_uxb.c")))

	if conf["SERVICE_CLI_SERVICE_DATA_PROCESS"] == "y":
		objs.append(env.Object(File("service_data_process.c")))

	if conf["SERVICE_CLI_DEVICE_DRIVER_SENSOR_OVER_CAN"] == "y":
		objs.append(env.Object(File("device_can_sensor.c")))

	if conf["SERVICE_CLI_DEVICE_CAN"] == "y":
		objs.append(env.Object(File("device_can.c")))

	if conf["SERVICE_CLI_SERVICE_PLOG_ROUTER"] == "y":
		objs.append(env.Object(File("service_plog_router.c")))

	if conf["SERVICE_CLI_SERVICE_PLOG_RELAY"] == "y":
		objs.append(env.Object(File("service_plog_relay.c")))

	if conf["SERVICE_CLI_DEVICE_CLOCK"] == "y":
		objs.append(env.Object(File("device_clock.c")))

	if conf["SERVICE_CLI_SYSTEM_BOOTLOADER"] == "y":
		objs.append(env.Object(File("system_bootloader.c")))
