Import("env")
Import("conf")
Import("objs")

objs.append(env.Object(source = [
	File("port.c"),
]))

# target and architecture specific configuration
env.Replace(LDSCRIPT = File("f411re.ld"))
env.Replace(LIBOCM3 = "opencm3_stm32f4")
env.Replace(OOCD_INTERFACE = "stlink-v2-1")
env.Replace(OOCD_TARGET = "stm32f4x_stlink")

env.Append(CFLAGS = [
	"-DSTM32F4",
])

env.Append(CPPPATH = [Dir(".")])

