Import("env")
Import("conf")
Import("objs")

if conf["LIB_BLAKE2S_MICRO"] == "y":

	env.Git('https://github.com/aykevl/blake2s-micro', branch='master')

	objs.append(env.Object([
		File(env['LIB_DEFAULT_REPO_DIR'] + 'blake2s.c'),
	]))

	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR']),
	])
