Import("env")
Import("conf")
Import("objs")

if conf["LIB_XZ_EMBEDDED"] == "y":

	env.Git("https://github.com/tukaani-project/xz-embedded", branch='master')

	# Enjoy your python
	decoders = ['-D' + k[4:] for k,v in conf.items() if k.startswith('LIB_XZ_DEC') and v == 'y']
	env.Append(CFLAGS = decoders)

	objs.append(env.Object([
		File(Glob(env['LIB_DEFAULT_REPO_DIR'] + '/linux/lib/xz/xz_crc32.c')),
		File(Glob(env['LIB_DEFAULT_REPO_DIR'] + '/linux/lib/xz/xz_dec_bcj.c')),
		File(Glob(env['LIB_DEFAULT_REPO_DIR'] + '/linux/lib/xz/xz_dec_lzma2.c')),
		File(Glob(env['LIB_DEFAULT_REPO_DIR'] + '/linux/lib/xz/xz_dec_stream.c')),
	]))

	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR']),
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/linux/include/linux'),
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/linux/lib/xz'),
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/userspace'),
	])
