Import("env")
Import("conf")
Import("objs")

if conf["LIB_HEATSHRINK"] == "y":

	env.Git("https://github.com/atomicobject/heatshrink", branch='v0.4.1')
	env.Patch("remove-fallthrough-warning.patch")

	objs.append(env.Object([
		"src/heatshrink_encoder.c",
		"src/heatshrink_decoder.c",
	]))
	
	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR']),
	])
