
/*
 * plumCore analog input interface
 *
 * Copyright (C) 2017, Marek Koza, qyx@krtko.org
 *
 * This file is part of uMesh node firmware (http://qyx.krtko.org/projects/umesh)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* Do not edit this file directly, it is autogenerated. */

#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#include "interface.h"


typedef enum {
	IADC_RET_OK,
	IADC_RET_FAILED,
} iadc_ret_t;

struct iadc_vmt {
	iadc_ret_t (*sample)(void *context, uint32_t input, int32_t *sample);
	void *context;
};

typedef struct {
	Interface interface;
	struct iadc_vmt vmt;
} IAdc;


iadc_ret_t iadc_sample(IAdc *self, uint32_t input, int32_t *sample);
iadc_ret_t iadc_init(IAdc *self);
iadc_ret_t iadc_free(IAdc *self);
