
/*
 * plumCore analog input interface
 *
 * Copyright (C) 2017, Marek Koza, qyx@krtko.org
 *
 * This file is part of uMesh node firmware (http://qyx.krtko.org/projects/umesh)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* Do not edit this file directly, it is autogenerated. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

#include "u_assert.h"
#include "interface.h"

#include "adc.h"

iadc_ret_t iadc_init(IAdc *self) {
	if(u_assert(self != NULL)) {
		return IADC_RET_FAILED;
	}

	memset(self, 0, sizeof(IAdc));
	uhal_interface_init(&self->interface);

	return IADC_RET_OK;
}


iadc_ret_t iadc_free(IAdc *self) {
	if(u_assert(self != NULL)) {
		return IADC_RET_FAILED;
	}

	return IADC_RET_OK;
}


iadc_ret_t iadc_sample(IAdc *self, uint32_t input, int32_t *sample) {
	if (self->vmt.sample != NULL) {
		return self->vmt.sample(self->vmt.context, input, sample);
	}

	return IADC_RET_FAILED;
}


