/* SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Common beeper sequences
 *
 * Copyright (c) 2026, Marek Koza (qyx@krtko.org)
 * All rights reserved.
 */

#pragma once

#include "beeper.h"

#define BEEPER_SEQ_SINGLE_BEEP BEEPER_SEQ { \
	BEEPER_SEQ_BEEP | BEEPER_SEQ_FREQ_HZ(1000) | BEEPER_SEQ_TIME_MS(100), \
	BEEPER_SEQ_WAIT | BEEPER_SEQ_TIME_MS(900), \
	BEEPER_SEQ_END \
} \

#define BEEPER_SEQ_DOUBLE_BEEP BEEPER_SEQ { \
	BEEPER_SEQ_BEEP | BEEPER_SEQ_FREQ_HZ(1000) | BEEPER_SEQ_TIME_MS(100), \
	BEEPER_SEQ_WAIT | BEEPER_SEQ_TIME_MS(100), \
	BEEPER_SEQ_BEEP | BEEPER_SEQ_FREQ_HZ(1000) | BEEPER_SEQ_TIME_MS(100), \
	BEEPER_SEQ_WAIT | BEEPER_SEQ_TIME_MS(700), \
	BEEPER_SEQ_END \
} \

#define BEEPER_SEQ_ALARM BEEPER_SEQ { \
	BEEPER_SEQ_BEEP | BEEPER_SEQ_FREQ_HZ(1000) | BEEPER_SEQ_TIME_MS(100), \
	BEEPER_SEQ_WAIT | BEEPER_SEQ_TIME_MS(100), \
	BEEPER_SEQ_BEEP | BEEPER_SEQ_FREQ_HZ(1000) | BEEPER_SEQ_TIME_MS(100), \
	BEEPER_SEQ_WAIT | BEEPER_SEQ_TIME_MS(700), \
	BEEPER_SEQ_REPEAT | BEEPER_SEQ_TIME_MS(2000), \
	BEEPER_SEQ_END \
} \

#define BEEPER_SEQ_LONG_BEEP BEEPER_SEQ { \
	BEEPER_SEQ_BEEP | BEEPER_SEQ_FREQ_HZ(1000) | BEEPER_SEQ_TIME_MS(500), \
	BEEPER_SEQ_WAIT | BEEPER_SEQ_TIME_MS(500), \
	BEEPER_SEQ_END \
} \

#define BEEPER_SEQ_ALERT BEEPER_SEQ { \
	BEEPER_SEQ_BEEP | BEEPER_SEQ_FREQ_HZ(2000) | BEEPER_SEQ_TIME_MS(200), \
	BEEPER_SEQ_WAIT | BEEPER_SEQ_TIME_MS(100), \
	BEEPER_SEQ_BEEP | BEEPER_SEQ_FREQ_HZ(1500) | BEEPER_SEQ_TIME_MS(200), \
	BEEPER_SEQ_WAIT | BEEPER_SEQ_TIME_MS(500), \
	BEEPER_SEQ_END \
} \

#define BEEPER_SEQ_STOP BEEPER_SEQ { \
	BEEPER_SEQ_WAIT | BEEPER_SEQ_TIME_MS(1000), \
	BEEPER_SEQ_END \
} \
