/* SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Input event subsystem
 *
 * Copyright (c) 2025, Marek Koza (qyx@krtko.org)
 * All rights reserved.
 */

#pragma once

#include <stdint.h>

/* Note that 'ev' shortcut is used in place of 'event' for enums. */

typedef enum {
	EV_RET_OK = 0,
	EV_RET_FAILED,
} event_ret_t;


/**
 * Event type defines the source of the event - where did the even come from?
 * Which kind of device generated the particular event?
 *
 * Declared with values usable as bit mask.
 */
enum event_type {
	EV_TYPE_NONE = 0,
	EV_TYPE_RAW = 1,
	EV_TYPE_REL = 2,
	EV_TYPE_ABS = 4,
	EV_TYPE_KEY = 8,
};

enum event_code {
	EV_CODE_NONE = 0,

	/**
	 * Raw and organic events directly from the source. No processing has been done now.
	 * Events are unique to the originating device only and need to be processed before
	 * being consumed.
	 *
	 * New raw events can be added when required.
	 */
	EV_RAW_0,  EV_RAW_1,  EV_RAW_2,  EV_RAW_3,  EV_RAW_4,  EV_RAW_5,  EV_RAW_6,  EV_RAW_7,
	EV_RAW_8,  EV_RAW_9,  EV_RAW_A,  EV_RAW_B,  EV_RAW_C,  EV_RAW_D,  EV_RAW_E,  EV_RAW_F,
	EV_RAW_10, EV_RAW_11, EV_RAW_12, EV_RAW_13, EV_RAW_14, EV_RAW_15, EV_RAW_16, EV_RAW_17,
	EV_RAW_18, EV_RAW_19, EV_RAW_1A, EV_RAW_1B, EV_RAW_1C, EV_RAW_1D, EV_RAW_1E, EV_RAW_1F,

	/**
	 * Relative cursor movement (eg. a knob/pulse encoder, a mouse)
	 */
	EV_REL_X,
	EV_REL_Y,

	/**
	 * Absolute cursor movement (knob with absolute encoder/potentiometer, touch screen
	 * position, etc.).
	 */
	EV_ABS_X,
	EV_ABS_Y,

	/**
	 * Keypad/keyboard/button events. Either directly generated by specialized
	 * services in simple systems (eg. a single diagnostic/Service button generating
	 * a EV_F1 event; or a more elaborate system with an event-mapper generating
	 * events based on a keypad layout.
	 *
	 * New events can be added when required. Consider mapping to an existing event,
	 * although not perfectly fitting, before introducing a new one.
	 */
	/* Control keys */
	EV_KEY_ENTER,
	EV_KEY_SPACE,
	EV_KEY_BACKSPACE,
	EV_KEY_TAB,
	EV_KEY_ESC,

	/* Array/cursor keys */
	EV_KEY_UP,
	EV_KEY_DOWN,
	EV_KEY_LEFT,
	EV_KEY_RIGHT,

	/* Finger touch event. */
	EV_KEY_TOUCH,

	/* Special function keys */
	EV_KEY_F1, EV_KEY_F2, EV_KEY_F3, EV_KEY_F4,
	EV_KEY_F5, EV_KEY_F6, EV_KEY_F7, EV_KEY_F8,

	/* Numeric keypad keys */
	EV_KEY_0, EV_KEY_1, EV_KEY_2, EV_KEY_3, EV_KEY_4,
	EV_KEY_5, EV_KEY_6, EV_KEY_7, EV_KEY_8, EV_KEY_9,
};

typedef struct event Event;

struct event_vmt {
	/**
	 * @brief Listen for an event
	 *
	 * Block the calling thread and wait for an event. It always blocks indefinitely.
	 * When returned with EV_RET_OK, @p type, @p code and @p value are filled with
	 * correct values corresponding to the received event.
	 *
	 * @param self Instance of the event source interface
	 * @param type Pointer to the variable receiving the type of the event
	 * @param code Pointer to the variable receiving the specific event
	 * @param value Pointer to the variable receiving the optional event
	 *              parameter/value. May be NULL.
	 *
	 * @return EV_RET_OK when an event was received and correctly processed,
	 *         EV_RET_FAILED otherwise.
	 */
	event_ret_t (*listen)(Event *self, enum event_type *type, enum event_code *code, int32_t *value);

	/**
	 * @brief Filter incoming events by type
	 *
	 * Sometimes it is beneficial to constrain received events to a specific type
	 * or types only, eg. we may want to receive key presses only. *p type parameter
	 * can be used as a bitmask like EV_REL | EV_ABS.
	 *
	 * @param @p type Type of the event/s to receive.
	 * @return EV_RET_OK when the filter was correctly applied,
	 *         EV_RET_FAILED otherwise.
	 */
	event_ret_t (*subscribe)(Event *self, enum event_type *type);
};

typedef struct event {
	const struct event_vmt *vmt;
	void *parent;
} Event;

