
/*
 * Interface for querying system services (see service locator pattern)
 *
 * Copyright (C) 2017, Marek Koza, qyx@krtko.org
 *
 * This file is part of uMesh node firmware (http://qyx.krtko.org/projects/umesh)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* Do not edit this file directly, it is autogenerated. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

#include "u_assert.h"
#include "interface.h"

#include "servicelocator.h"

iservicelocator_ret_t iservicelocator_init(IServiceLocator *self) {
	if(u_assert(self != NULL)) {
		return ISERVICELOCATOR_RET_FAILED;
	}

	memset(self, 0, sizeof(IServiceLocator));
	uhal_interface_init(&self->interface);

	return ISERVICELOCATOR_RET_OK;
}


iservicelocator_ret_t iservicelocator_free(IServiceLocator *self) {
	if(u_assert(self != NULL)) {
		return ISERVICELOCATOR_RET_FAILED;
	}

	return ISERVICELOCATOR_RET_OK;
}


iservicelocator_ret_t iservicelocator_set_name(IServiceLocator *self, Interface * interface, const char * name) {
	if (self->vmt.set_name != NULL) {
		return self->vmt.set_name(self->vmt.context, interface, name);
	}

	return ISERVICELOCATOR_RET_FAILED;
}


iservicelocator_ret_t iservicelocator_add(IServiceLocator *self, enum iservicelocator_type type, Interface * interface, char * name) {
	if (self->vmt.add != NULL) {
		return self->vmt.add(self->vmt.context, type, interface, name);
	}

	return ISERVICELOCATOR_RET_FAILED;
}


iservicelocator_ret_t iservicelocator_query_name(IServiceLocator *self, char * name, Interface ** result) {
	if (self->vmt.query_name != NULL) {
		return self->vmt.query_name(self->vmt.context, name, result);
	}

	return ISERVICELOCATOR_RET_FAILED;
}


iservicelocator_ret_t iservicelocator_query_type_id(IServiceLocator *self, enum iservicelocator_type type, size_t index, Interface ** result) {
	if (self->vmt.query_type_id != NULL) {
		return self->vmt.query_type_id(self->vmt.context, type, index, result);
	}

	return ISERVICELOCATOR_RET_FAILED;
}


iservicelocator_ret_t iservicelocator_query_type_next(IServiceLocator *self, enum iservicelocator_type type, Interface * start, Interface ** result) {
	if (self->vmt.query_type_next != NULL) {
		return self->vmt.query_type_next(self->vmt.context, type, start, result);
	}

	return ISERVICELOCATOR_RET_FAILED;
}


iservicelocator_ret_t iservicelocator_query_name_type(IServiceLocator *self, char * name, enum iservicelocator_type type, Interface ** result) {
	if (self->vmt.query_name_type != NULL) {
		return self->vmt.query_name_type(self->vmt.context, name, type, result);
	}

	return ISERVICELOCATOR_RET_FAILED;
}


iservicelocator_ret_t iservicelocator_get_name(IServiceLocator *self, Interface * interface, const char ** result) {
	if (self->vmt.get_name != NULL) {
		return self->vmt.get_name(self->vmt.context, interface, result);
	}

	return ISERVICELOCATOR_RET_FAILED;
}


