
/*
 * UXB bus interface
 *
 * Copyright (C) 2017, Marek Koza, qyx@krtko.org
 *
 * This file is part of uMesh node firmware (http://qyx.krtko.org/projects/umesh)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* Do not edit this file directly, it is autogenerated. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

#include "u_assert.h"
#include "interface.h"

#include "uxbbus.h"

iuxbbus_ret_t iuxbbus_init(IUxbBus *self) {
	if(u_assert(self != NULL)) {
		return IUXBBUS_RET_FAILED;
	}

	memset(self, 0, sizeof(IUxbBus));
	uhal_interface_init(&self->interface);

	return IUXBBUS_RET_OK;
}


iuxbbus_ret_t iuxbbus_free(IUxbBus *self) {
	if(u_assert(self != NULL)) {
		return IUXBBUS_RET_FAILED;
	}

	return IUXBBUS_RET_OK;
}


iuxbbus_ret_t iuxbbus_add_device(IUxbBus *self, IUxbDevice ** device) {
	if (self->vmt.add_device != NULL) {
		return self->vmt.add_device(self->vmt.context, device);
	}

	return IUXBBUS_RET_FAILED;
}


iuxbbus_ret_t iuxbbus_probe_device(IUxbBus *self, uint8_t * address, bool * result) {
	if (self->vmt.probe_device != NULL) {
		return self->vmt.probe_device(self->vmt.context, address, result);
	}

	return IUXBBUS_RET_FAILED;
}


iuxbbus_ret_t iuxbbus_remove_device(IUxbBus *self, IUxbDevice * device) {
	if (self->vmt.remove_device != NULL) {
		return self->vmt.remove_device(self->vmt.context, device);
	}

	return IUXBBUS_RET_FAILED;
}


