
/*
 * UXB bus interface
 *
 * Copyright (C) 2017, Marek Koza, qyx@krtko.org
 *
 * This file is part of uMesh node firmware (http://qyx.krtko.org/projects/umesh)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* Do not edit this file directly, it is autogenerated. */

#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#include "interface.h"


#include "interfaces/uxbdevice.h"
typedef enum {
	IUXBBUS_RET_OK,
	IUXBBUS_RET_FAILED,
} iuxbbus_ret_t;

struct iuxbbus_vmt {
	iuxbbus_ret_t (*add_device)(void *context, IUxbDevice ** device);
	iuxbbus_ret_t (*probe_device)(void *context, uint8_t * address, bool * result);
	iuxbbus_ret_t (*remove_device)(void *context, IUxbDevice * device);
	void *context;
};

typedef struct {
	Interface interface;
	struct iuxbbus_vmt vmt;
} IUxbBus;


iuxbbus_ret_t iuxbbus_add_device(IUxbBus *self, IUxbDevice ** device);
iuxbbus_ret_t iuxbbus_init(IUxbBus *self);
iuxbbus_ret_t iuxbbus_probe_device(IUxbBus *self, uint8_t * address, bool * result);
iuxbbus_ret_t iuxbbus_remove_device(IUxbBus *self, IUxbDevice * device);
iuxbbus_ret_t iuxbbus_free(IUxbBus *self);
