
/*
 * UXB slot interface
 *
 * Copyright (C) 2017, Marek Koza, qyx@krtko.org
 *
 * This file is part of uMesh node firmware (http://qyx.krtko.org/projects/umesh)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* Do not edit this file directly, it is autogenerated. */

#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#include "interface.h"


typedef enum {
	IUXBSLOT_RET_OK,
	IUXBSLOT_RET_FAILED,
} iuxbslot_ret_t;

struct iuxbslot_vmt {
	iuxbslot_ret_t (*receive)(void *context, uint8_t * buf, size_t size, size_t * len);
	iuxbslot_ret_t (*send)(void *context, const uint8_t * buf, size_t len, bool response);
	iuxbslot_ret_t (*set_slot_number)(void *context, uint8_t slot_number);
	iuxbslot_ret_t (*set_slot_buffer)(void *context, uint8_t * buf, size_t len);
	void *context;
};

typedef struct {
	Interface interface;
	struct iuxbslot_vmt vmt;
} IUxbSlot;


iuxbslot_ret_t iuxbslot_receive(IUxbSlot *self, uint8_t * buf, size_t size, size_t * len);
iuxbslot_ret_t iuxbslot_free(IUxbSlot *self);
iuxbslot_ret_t iuxbslot_init(IUxbSlot *self);
iuxbslot_ret_t iuxbslot_send(IUxbSlot *self, const uint8_t * buf, size_t len, bool response);
iuxbslot_ret_t iuxbslot_set_slot_number(IUxbSlot *self, uint8_t slot_number);
iuxbslot_ret_t iuxbslot_set_slot_buffer(IUxbSlot *self, uint8_t * buf, size_t len);
