
/*
 * UXB slot interface
 *
 * Copyright (C) 2017, Marek Koza, qyx@krtko.org
 *
 * This file is part of uMesh node firmware (http://qyx.krtko.org/projects/umesh)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* Do not edit this file directly, it is autogenerated. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

#include "u_assert.h"
#include "interface.h"

#include "uxbslot.h"

iuxbslot_ret_t iuxbslot_init(IUxbSlot *self) {
	if(u_assert(self != NULL)) {
		return IUXBSLOT_RET_FAILED;
	}

	memset(self, 0, sizeof(IUxbSlot));
	uhal_interface_init(&self->interface);

	return IUXBSLOT_RET_OK;
}


iuxbslot_ret_t iuxbslot_free(IUxbSlot *self) {
	if(u_assert(self != NULL)) {
		return IUXBSLOT_RET_FAILED;
	}

	return IUXBSLOT_RET_OK;
}


iuxbslot_ret_t iuxbslot_receive(IUxbSlot *self, uint8_t * buf, size_t size, size_t * len) {
	if (self->vmt.receive != NULL) {
		return self->vmt.receive(self->vmt.context, buf, size, len);
	}

	return IUXBSLOT_RET_FAILED;
}


iuxbslot_ret_t iuxbslot_send(IUxbSlot *self, const uint8_t * buf, size_t len, bool response) {
	if (self->vmt.send != NULL) {
		return self->vmt.send(self->vmt.context, buf, len, response);
	}

	return IUXBSLOT_RET_FAILED;
}


iuxbslot_ret_t iuxbslot_set_slot_number(IUxbSlot *self, uint8_t slot_number) {
	if (self->vmt.set_slot_number != NULL) {
		return self->vmt.set_slot_number(self->vmt.context, slot_number);
	}

	return IUXBSLOT_RET_FAILED;
}


iuxbslot_ret_t iuxbslot_set_slot_buffer(IUxbSlot *self, uint8_t * buf, size_t len) {
	if (self->vmt.set_slot_buffer != NULL) {
		return self->vmt.set_slot_buffer(self->vmt.context, buf, len);
	}

	return IUXBSLOT_RET_FAILED;
}


