import os
Import("env")

env.Command(
	source = Glob("interfaces/*.yaml"),
	target = [
		"interfaces/servicelocator.c",
		"interfaces/servicelocator.h",
	],
	action = Action("python tools/interface_generator.py $SOURCE", env['GENIFACECOMSTR'])
)

objs = env.Object(source = [
	File(Glob("*.c")),
	File(Glob("interfaces/*.c")),
	File(Glob("interfaces/plog/*.c")),
	File(Glob("interfaces/clock/*.c")),
])

env.Append(CPPPATH = [
	Dir("."),
	Dir("interfaces"),

])

for d in next(os.walk("."))[1]:
	f = os.path.join(d, "SConscript")
	if os.path.isfile(f):
		SConscript(f)


Return("objs")
