Import("env")
Import("conf")
Import("objs")

if conf["LIB_DUKTAPE"] == "y":

	env.Git('https://github.com/svaarala/duktape', branch='v2.6-maintenance')

	ddir = env['LIB_DEFAULT_REPO_DIR']

	# Build actions run from the project root, but LIB_DEFAULT_REPO_DIR is relative to this
	# SConscript directory, so resolve it to an absolute path for the command line.
	rdir = Dir(ddir).abspath

	# TODO: rewrite filenames
	duktape = env.Command(
		source = None,
		target = [
			File(f'{ddir}/src-custom/duktape.c'),
			File(f'{ddir}/src-custom/duktape.h')
		],
		action = f'python {rdir}/tools/configure.py --output-directory {rdir}/src-custom --source-directory {rdir}/src-input --config-metadata {rdir}/config --option-file {rdir}/config/examples/low_memory.yaml -DDUK_USE_FASTINT --rom-support',
	)

	objs.append(env.Object([
		File(f'{ddir}/src-custom/duktape.c'),
	]))

	env.Append(CPPPATH = [
		Dir(f'{ddir}/src-custom'),
	])

