Import("env")
Import("conf")
Import("objs")

if conf["LIB_SPIFFS"] == "y":

	env.Git('https://github.com/pellepl/spiffs', branch='master')

	objs.append(env.Object([
		File(Glob(env['LIB_DEFAULT_REPO_DIR'] + '/src/*.c')),
	]))

	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/src'),
	])
