/* SPDX-License-Identifier: GPL-3.0-or-later
 *
 * 1-Wire bus master over a UART peripheral
 *
 * Copyright (c) 2026, Marek Koza (qyx@krtko.org)
 * All rights reserved.
 */

#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <main.h>

#include <interfaces/uart.h>
#include <interfaces/stream.h>
#include <interfaces/ow.h>

/*
 * This service drives a 1-Wire(R) bus using a UART peripheral configured for open-drain single-wire half-duplex
 * operation, using the well known "one UART byte per 1-Wire bit" scheme: the bus reset is generated by sending 0xF0
 * at 9600 baud while individual read/write bit slots are generated at 115200 baud. It therefore needs both the Uart
 * interface (to switch the bitrate between the reset and the bit slots) and the Stream interface (to shift the bytes
 * in and out) of the same underlying UART device. It provides the generic Ow bus master interface.
 */

typedef struct uart_ow {
	Uart *uart;
	Stream *stream;

	/* Provided interface. */
	Ow ow;
} UartOw;


ow_ret_t uart_ow_init(UartOw *self, Uart *uart, Stream *stream);
ow_ret_t uart_ow_free(UartOw *self);

/* Obtain the Ow bus master interface. */
ow_ret_t uart_ow_get_ow(UartOw *self, Ow **ow);
