Import("env")

objs = env.Object(source = [
	File(Glob("*.c")),
])

env.Append(CPPPATH = [
	Dir("."),

])

env.DependsOnModule("services/plog-sensor-upload")
env.DependsOnModule("services/data-process")
env.DependsOnModule("services/plog-packager")
env.DependsOnModule("services/plog-router")
env.DependsOnModule("services/cli")

Return("objs")
