/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Fri May 19 19:11:33 2017. */

#include "ake_3dh.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Ake3dhMessage_fields[8] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, Ake3dhMessage, session_id, session_id, 0),
    PB_ONEOF_FIELD(content,   2, MESSAGE , ONEOF, STATIC  , OTHER, Ake3dhMessage, epk_request, session_id, &EphemeralPublicKeyRequest_fields),
    PB_ONEOF_FIELD(content,   3, MESSAGE , ONEOF, STATIC  , OTHER, Ake3dhMessage, epk_response, session_id, &EphemeralPublicKeyResponse_fields),
    PB_ONEOF_FIELD(content,   4, MESSAGE , ONEOF, STATIC  , OTHER, Ake3dhMessage, ipk_request, session_id, &IdentityPublicKeyRequest_fields),
    PB_ONEOF_FIELD(content,   5, MESSAGE , ONEOF, STATIC  , OTHER, Ake3dhMessage, ipk_response, session_id, &IdentityPublicKeyResponse_fields),
    PB_ONEOF_FIELD(content,   6, MESSAGE , ONEOF, STATIC  , OTHER, Ake3dhMessage, kc_request, session_id, &KeyConfirmationRequest_fields),
    PB_ONEOF_FIELD(content,   7, MESSAGE , ONEOF, STATIC  , OTHER, Ake3dhMessage, kc_response, session_id, &KeyConfirmationResponse_fields),
    PB_LAST_FIELD
};

const pb_field_t EphemeralPublicKeyRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t EphemeralPublicKeyResponse_fields[2] = {
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , FIRST, EphemeralPublicKeyResponse, ephemeral_pk, ephemeral_pk, 0),
    PB_LAST_FIELD
};

const pb_field_t IdentityPublicKeyRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t IdentityPublicKeyResponse_fields[3] = {
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , FIRST, IdentityPublicKeyResponse, identity_pk, identity_pk, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, IdentityPublicKeyResponse, encrypted_identity_pk, identity_pk, 0),
    PB_LAST_FIELD
};

const pb_field_t KeyConfirmationRequest_fields[2] = {
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , FIRST, KeyConfirmationRequest, challenge, challenge, 0),
    PB_LAST_FIELD
};

const pb_field_t KeyConfirmationResponse_fields[2] = {
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , FIRST, KeyConfirmationResponse, response, response, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Ake3dhMessage, content.epk_request) < 65536 && pb_membersize(Ake3dhMessage, content.epk_response) < 65536 && pb_membersize(Ake3dhMessage, content.ipk_request) < 65536 && pb_membersize(Ake3dhMessage, content.ipk_response) < 65536 && pb_membersize(Ake3dhMessage, content.kc_request) < 65536 && pb_membersize(Ake3dhMessage, content.kc_response) < 65536 && pb_membersize(Ake3dhMessage, content.epk_request) < 65536 && pb_membersize(Ake3dhMessage, content.epk_response) < 65536 && pb_membersize(Ake3dhMessage, content.ipk_request) < 65536 && pb_membersize(Ake3dhMessage, content.ipk_response) < 65536 && pb_membersize(Ake3dhMessage, content.kc_request) < 65536 && pb_membersize(Ake3dhMessage, content.kc_response) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Ake3dhMessage_EphemeralPublicKeyRequest_EphemeralPublicKeyResponse_IdentityPublicKeyRequest_IdentityPublicKeyResponse_KeyConfirmationRequest_KeyConfirmationResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Ake3dhMessage, content.epk_request) < 256 && pb_membersize(Ake3dhMessage, content.epk_response) < 256 && pb_membersize(Ake3dhMessage, content.ipk_request) < 256 && pb_membersize(Ake3dhMessage, content.ipk_response) < 256 && pb_membersize(Ake3dhMessage, content.kc_request) < 256 && pb_membersize(Ake3dhMessage, content.kc_response) < 256 && pb_membersize(Ake3dhMessage, content.epk_request) < 256 && pb_membersize(Ake3dhMessage, content.epk_response) < 256 && pb_membersize(Ake3dhMessage, content.ipk_request) < 256 && pb_membersize(Ake3dhMessage, content.ipk_response) < 256 && pb_membersize(Ake3dhMessage, content.kc_request) < 256 && pb_membersize(Ake3dhMessage, content.kc_response) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Ake3dhMessage_EphemeralPublicKeyRequest_EphemeralPublicKeyResponse_IdentityPublicKeyRequest_IdentityPublicKeyResponse_KeyConfirmationRequest_KeyConfirmationResponse)
#endif


/* @@protoc_insertion_point(eof) */
