/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Fri May 19 19:11:33 2017. */

#include "file_transfer.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t FileTransferMessage_fields[6] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, FileTransferMessage, session_id, session_id, 0),
    PB_ONEOF_FIELD(content,   2, MESSAGE , ONEOF, STATIC  , OTHER, FileTransferMessage, file_metadata, session_id, &FileMetadata_fields),
    PB_ONEOF_FIELD(content,   3, MESSAGE , ONEOF, STATIC  , OTHER, FileTransferMessage, file_request, session_id, &FileRequest_fields),
    PB_ONEOF_FIELD(content,   4, MESSAGE , ONEOF, STATIC  , OTHER, FileTransferMessage, block_request, session_id, &BlockRequest_fields),
    PB_ONEOF_FIELD(content,   5, MESSAGE , ONEOF, STATIC  , OTHER, FileTransferMessage, block_response, session_id, &BlockResponse_fields),
    PB_LAST_FIELD
};

const pb_field_t FileMetadata_fields[7] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, FileMetadata, piece_size_blocks, piece_size_blocks, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, FileMetadata, file_size_bytes, piece_size_blocks, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, FileMetadata, file_name, file_size_bytes, 0),
    PB_ONEOF_FIELD(check,   4, BYTES   , ONEOF, STATIC  , OTHER, FileMetadata, crc32, file_name, 0),
    PB_ONEOF_FIELD(check,   5, BYTES   , ONEOF, STATIC  , OTHER, FileMetadata, sha2_256, file_name, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, FileMetadata, block_size_bytes, check.sha2_256, 0),
    PB_LAST_FIELD
};

const pb_field_t FileRequest_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, FileRequest, file_name, file_name, 0),
    PB_LAST_FIELD
};

const pb_field_t BlockRequest_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, BlockRequest, piece, piece, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, BlockRequest, bitmap, piece, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, BlockRequest, transferred_pieces, bitmap, 0),
    PB_LAST_FIELD
};

const pb_field_t BlockResponse_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, BlockResponse, piece, piece, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, BlockResponse, block, piece, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, STATIC  , OTHER, BlockResponse, data, block, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FileTransferMessage, content.file_metadata) < 65536 && pb_membersize(FileTransferMessage, content.file_request) < 65536 && pb_membersize(FileTransferMessage, content.block_request) < 65536 && pb_membersize(FileTransferMessage, content.block_response) < 65536 && pb_membersize(FileTransferMessage, content.file_metadata) < 65536 && pb_membersize(FileTransferMessage, content.file_request) < 65536 && pb_membersize(FileTransferMessage, content.block_request) < 65536 && pb_membersize(FileTransferMessage, content.block_response) < 65536 && pb_membersize(FileTransferMessage, content.file_metadata) < 65536 && pb_membersize(FileTransferMessage, content.file_request) < 65536 && pb_membersize(FileTransferMessage, content.block_request) < 65536 && pb_membersize(FileTransferMessage, content.block_response) < 65536 && pb_membersize(FileTransferMessage, content.file_metadata) < 65536 && pb_membersize(FileTransferMessage, content.file_request) < 65536 && pb_membersize(FileTransferMessage, content.block_request) < 65536 && pb_membersize(FileTransferMessage, content.block_response) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_FileTransferMessage_FileMetadata_FileRequest_BlockRequest_BlockResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FileTransferMessage, content.file_metadata) < 256 && pb_membersize(FileTransferMessage, content.file_request) < 256 && pb_membersize(FileTransferMessage, content.block_request) < 256 && pb_membersize(FileTransferMessage, content.block_response) < 256 && pb_membersize(FileTransferMessage, content.file_metadata) < 256 && pb_membersize(FileTransferMessage, content.file_request) < 256 && pb_membersize(FileTransferMessage, content.block_request) < 256 && pb_membersize(FileTransferMessage, content.block_response) < 256 && pb_membersize(FileTransferMessage, content.file_metadata) < 256 && pb_membersize(FileTransferMessage, content.file_request) < 256 && pb_membersize(FileTransferMessage, content.block_request) < 256 && pb_membersize(FileTransferMessage, content.block_response) < 256 && pb_membersize(FileTransferMessage, content.file_metadata) < 256 && pb_membersize(FileTransferMessage, content.file_request) < 256 && pb_membersize(FileTransferMessage, content.block_request) < 256 && pb_membersize(FileTransferMessage, content.block_response) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_FileTransferMessage_FileMetadata_FileRequest_BlockRequest_BlockResponse)
#endif


/* @@protoc_insertion_point(eof) */
