/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Fri May 19 19:11:33 2017. */

#include "umesh_l2_keymgr.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t L2KeyManagerMessage_fields[2] = {
    PB_ONEOF_FIELD(content,   1, MESSAGE , ONEOF, STATIC  , FIRST, L2KeyManagerMessage, ake_3dh, ake_3dh, &Ake3dhMessage_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(L2KeyManagerMessage, content.ake_3dh) < 65536 && pb_membersize(L2KeyManagerMessage, content.ake_3dh) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_L2KeyManagerMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(L2KeyManagerMessage, content.ake_3dh) < 256 && pb_membersize(L2KeyManagerMessage, content.ake_3dh) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_L2KeyManagerMessage)
#endif


/* @@protoc_insertion_point(eof) */
