/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Fri May 19 19:11:33 2017. */

#include "umesh_l2_status.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t StatusProtoMessage_fields[3] = {
    PB_ONEOF_FIELD(content,   1, MESSAGE , ONEOF, STATIC  , FIRST, StatusProtoMessage, sensor_message, sensor_message, &SensorMessage_fields),
    PB_ONEOF_FIELD(content,   2, MESSAGE , ONEOF, STATIC  , FIRST, StatusProtoMessage, power_message, power_message, &PowerMessage_fields),
    PB_LAST_FIELD
};

const pb_field_t SensorMessage_fields[7] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, SensorMessage, id, id, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, SensorMessage, quantity_name, id, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, SensorMessage, quantity_symbol, quantity_name, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, SensorMessage, unit_name, quantity_symbol, 0),
    PB_FIELD(  5, BYTES   , REQUIRED, STATIC  , OTHER, SensorMessage, unit_symbol, unit_name, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, SensorMessage, value, unit_symbol, 0),
    PB_LAST_FIELD
};

const pb_field_t PowerMessage_fields[4] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, PowerMessage, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, PowerMessage, voltage, id, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, PowerMessage, current, voltage, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(StatusProtoMessage, content.sensor_message) < 65536 && pb_membersize(StatusProtoMessage, content.power_message) < 65536 && pb_membersize(StatusProtoMessage, content.sensor_message) < 65536 && pb_membersize(StatusProtoMessage, content.power_message) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_StatusProtoMessage_SensorMessage_PowerMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(StatusProtoMessage, content.sensor_message) < 256 && pb_membersize(StatusProtoMessage, content.power_message) < 256 && pb_membersize(StatusProtoMessage, content.sensor_message) < 256 && pb_membersize(StatusProtoMessage, content.power_message) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_StatusProtoMessage_SensorMessage_PowerMessage)
#endif


/* @@protoc_insertion_point(eof) */
