Import("env")
Import("conf")
Import("objs")

if conf["LIB_TINYCBOR"] == "y":

	env.Git('https://github.com/intel/tinycbor', branch='main')
	env.Patch([
		'add-create-byte-string-array.patch',
		'add-default-case.patch',
		'fix-undefined-flt16.patch',
	])

	env.Command(
		File(env['LIB_DEFAULT_REPO_DIR'] + '/src/tinycbor-version.h'),
		File(env['LIB_DEFAULT_REPO_DIR'] + '/src/tinycbor-version.h.in'),
		Copy("$TARGET", "$SOURCE")
	)
	env.Command(
		File(env['LIB_DEFAULT_REPO_DIR'] + '/src/tinycbor-export.h'),
		File(env['LIB_DEFAULT_REPO_DIR'] + '/src/tinycbor-export.h.in'),
		Copy("$TARGET", "$SOURCE")
	)

	objs.append(env.Object([
		File(env['LIB_DEFAULT_REPO_DIR'] + '/src/cborparser.c'),
		File(env['LIB_DEFAULT_REPO_DIR'] + '/src/cborencoder.c'),
	]))

	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/src'),
	])
