Import("env")
Import("conf")
Import("objs")

if conf["LIB_PLUMCORE_CRYPTOLIB"] == "y":

	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR']),
	])

	# External cryptolib; suppress its warning flavours only for these objects.
	cryptolib_env = env.Clone()
	cryptolib_env.Append(CFLAGS = [
		'-Wno-cast-qual',
		'-Wno-sign-compare',
	])
	objs.append(cryptolib_env.Object([
		File(Glob(env['LIB_DEFAULT_REPO_DIR'] + '*.c')),
	]))
