Import("env")
Import("conf")
Import("objs")

if conf["LIB_ZFP"] == "y":

	env.Git('https://github.com/LLNL/zfp', branch='develop')

	env.Append(CFLAGS = ['-DZFP_ROUNDING_MODE=0'])
	objs.append(env.Object([
		File(Glob(env['LIB_DEFAULT_REPO_DIR'] + '/src/*.c')),
	]))
	
	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/src'),
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/include'),
	])
