import os

Import("env")

# Build all interface files from the YAML definitions
env.Command(
	source = Glob("interfaces/*.yaml"),
	target = [
		"interfaces/adc.c",
		"interfaces/adc.h"
	],
	action = Action("python tools/interface_generator.py $SOURCE", env['GENIFACECOMSTR'])
)


objs = env.Object(source = [
	File(Glob("common/*.c")),
	File(Glob("interfaces/*.c")),
	File(Glob("modules/*.c")),
])


# Do not append uHal subdirectories to the CPPPATH variable.
# Header files should be referenced with #include <uhal/interfaces/...>
env.Append(CPPPATH = [
	Dir("."),
	Dir("common"),
])

Return("objs")
