Import("env")
Import("objs")
Import("conf")

if conf["SERVICE_CRASH_MGR"] == "y":
	env.Component()
	objs.append(env.Object(File(Glob("*.c"))))

if conf["CRASH_MGR_ENABLE_BACKTRACE"] == "y":
	env.Append(CFLAGS = ["-funwind-tables"])

	if conf["CRASH_MGR_FUNCTION_NAMES"] == "y":
		env.Append(CFLAGS = ["-mpoke-function-name"])

