# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: umesh_cert.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='umesh_cert.proto',
  package='',
  serialized_pb=_b('\n\x10umesh_cert.proto\x1a\x0cnanopb.proto\"/\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x02(\x05\x12\x0b\n\x03\x64\x61y\x18\x02 \x01(\x05\x12\x0c\n\x04time\x18\x03 \x01(\x05\"A\n\x03Key\x12\x17\n\x08identity\x18\x01 \x02(\x0c\x42\x05\x92?\x02\x08 \x12\x1b\n\ned25519_sk\x18\x02 \x01(\x0c\x42\x05\x92?\x02\x08 H\x00\x42\x04\n\x02sk\"\xea\x01\n\x15\x43\x65rtificateSignedData\x12\x17\n\x08identity\x18\x01 \x02(\x0c\x42\x05\x92?\x02\x08 \x12\x19\n\nvalid_from\x18\x02 \x01(\x0b\x32\x05.Date\x12\x17\n\x08valid_to\x18\x03 \x01(\x0b\x32\x05.Date\x12\x1b\n\x0cgenerated_on\x18\x04 \x01(\x0b\x32\x05.Date\x12\x14\n\x0csubject_name\x18\x05 \x01(\t\x12\x15\n\rsubject_email\x18\x06 \x01(\t\x12\x17\n\x0fsubject_comment\x18\x07 \x01(\t\x12\x1b\n\ned25519_pk\x18\x08 \x01(\x0c\x42\x05\x92?\x02\x08 H\x00\x42\x04\n\x02pk\"\x91\x01\n\x18\x43\x65rtificateSignatureData\x12\x18\n\tsigned_on\x18\x01 \x01(\x0b\x32\x05.Date\x12\x19\n\nvalid_from\x18\x02 \x01(\x0b\x32\x05.Date\x12\x17\n\x08valid_to\x18\x03 \x01(\x0b\x32\x05.Date\x12\'\n\x0btrust_level\x18\x04 \x01(\x0e\x32\x12.SubjectTrustLevel\"\xe7\x01\n\x14\x43\x65rtificateSignature\x12\x31\n\x0esignature_data\x18\x01 \x02(\x0b\x32\x19.CertificateSignatureData\x12\x1e\n\x0fsigner_identity\x18\x02 \x02(\x0c\x42\x05\x92?\x02\x08 \x12\x1f\n\x10subject_identity\x18\x03 \x01(\x0c\x42\x05\x92?\x02\x08 \x12*\n\x10\x64igest_algorithm\x18\x04 \x02(\x0e\x32\x10.DigestAlgorithm\x12\"\n\x11\x65\x64\x32\x35\x35\x31\x39_signature\x18\x05 \x01(\x0c\x42\x05\x92?\x02\x08@H\x00\x42\x0b\n\tsignature\"`\n\x0b\x43\x65rtificate\x12\'\n\x07\x63ontent\x18\x01 \x02(\x0b\x32\x16.CertificateSignedData\x12(\n\tsignature\x18\x02 \x03(\x0b\x32\x15.CertificateSignature*-\n\x0f\x44igestAlgorithm\x12\x0c\n\x08SHA2_256\x10\x01\x12\x0c\n\x08SHA3_256\x10\x02*@\n\x11SubjectTrustLevel\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04HIGH\x10\x03\x12\x0c\n\x08ULTIMATE\x10\x04')
  ,
  dependencies=[nanopb_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DIGESTALGORITHM = _descriptor.EnumDescriptor(
  name='DigestAlgorithm',
  full_name='DigestAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SHA2_256', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA3_256', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=867,
  serialized_end=912,
)
_sym_db.RegisterEnumDescriptor(_DIGESTALGORITHM)

DigestAlgorithm = enum_type_wrapper.EnumTypeWrapper(_DIGESTALGORITHM)
_SUBJECTTRUSTLEVEL = _descriptor.EnumDescriptor(
  name='SubjectTrustLevel',
  full_name='SubjectTrustLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOW', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ULTIMATE', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=914,
  serialized_end=978,
)
_sym_db.RegisterEnumDescriptor(_SUBJECTTRUSTLEVEL)

SubjectTrustLevel = enum_type_wrapper.EnumTypeWrapper(_SUBJECTTRUSTLEVEL)
SHA2_256 = 1
SHA3_256 = 2
LOW = 1
MEDIUM = 2
HIGH = 3
ULTIMATE = 4



_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='Date.year', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='day', full_name='Date.day', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='Date.time', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=81,
)


_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity', full_name='Key.identity', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))),
    _descriptor.FieldDescriptor(
      name='ed25519_sk', full_name='Key.ed25519_sk', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sk', full_name='Key.sk',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=83,
  serialized_end=148,
)


_CERTIFICATESIGNEDDATA = _descriptor.Descriptor(
  name='CertificateSignedData',
  full_name='CertificateSignedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity', full_name='CertificateSignedData.identity', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))),
    _descriptor.FieldDescriptor(
      name='valid_from', full_name='CertificateSignedData.valid_from', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valid_to', full_name='CertificateSignedData.valid_to', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='generated_on', full_name='CertificateSignedData.generated_on', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subject_name', full_name='CertificateSignedData.subject_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subject_email', full_name='CertificateSignedData.subject_email', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subject_comment', full_name='CertificateSignedData.subject_comment', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ed25519_pk', full_name='CertificateSignedData.ed25519_pk', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='pk', full_name='CertificateSignedData.pk',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=151,
  serialized_end=385,
)


_CERTIFICATESIGNATUREDATA = _descriptor.Descriptor(
  name='CertificateSignatureData',
  full_name='CertificateSignatureData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signed_on', full_name='CertificateSignatureData.signed_on', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valid_from', full_name='CertificateSignatureData.valid_from', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valid_to', full_name='CertificateSignatureData.valid_to', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trust_level', full_name='CertificateSignatureData.trust_level', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=533,
)


_CERTIFICATESIGNATURE = _descriptor.Descriptor(
  name='CertificateSignature',
  full_name='CertificateSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature_data', full_name='CertificateSignature.signature_data', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signer_identity', full_name='CertificateSignature.signer_identity', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))),
    _descriptor.FieldDescriptor(
      name='subject_identity', full_name='CertificateSignature.subject_identity', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))),
    _descriptor.FieldDescriptor(
      name='digest_algorithm', full_name='CertificateSignature.digest_algorithm', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ed25519_signature', full_name='CertificateSignature.ed25519_signature', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010@'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='signature', full_name='CertificateSignature.signature',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=536,
  serialized_end=767,
)


_CERTIFICATE = _descriptor.Descriptor(
  name='Certificate',
  full_name='Certificate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='Certificate.content', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Certificate.signature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=769,
  serialized_end=865,
)

_KEY.oneofs_by_name['sk'].fields.append(
  _KEY.fields_by_name['ed25519_sk'])
_KEY.fields_by_name['ed25519_sk'].containing_oneof = _KEY.oneofs_by_name['sk']
_CERTIFICATESIGNEDDATA.fields_by_name['valid_from'].message_type = _DATE
_CERTIFICATESIGNEDDATA.fields_by_name['valid_to'].message_type = _DATE
_CERTIFICATESIGNEDDATA.fields_by_name['generated_on'].message_type = _DATE
_CERTIFICATESIGNEDDATA.oneofs_by_name['pk'].fields.append(
  _CERTIFICATESIGNEDDATA.fields_by_name['ed25519_pk'])
_CERTIFICATESIGNEDDATA.fields_by_name['ed25519_pk'].containing_oneof = _CERTIFICATESIGNEDDATA.oneofs_by_name['pk']
_CERTIFICATESIGNATUREDATA.fields_by_name['signed_on'].message_type = _DATE
_CERTIFICATESIGNATUREDATA.fields_by_name['valid_from'].message_type = _DATE
_CERTIFICATESIGNATUREDATA.fields_by_name['valid_to'].message_type = _DATE
_CERTIFICATESIGNATUREDATA.fields_by_name['trust_level'].enum_type = _SUBJECTTRUSTLEVEL
_CERTIFICATESIGNATURE.fields_by_name['signature_data'].message_type = _CERTIFICATESIGNATUREDATA
_CERTIFICATESIGNATURE.fields_by_name['digest_algorithm'].enum_type = _DIGESTALGORITHM
_CERTIFICATESIGNATURE.oneofs_by_name['signature'].fields.append(
  _CERTIFICATESIGNATURE.fields_by_name['ed25519_signature'])
_CERTIFICATESIGNATURE.fields_by_name['ed25519_signature'].containing_oneof = _CERTIFICATESIGNATURE.oneofs_by_name['signature']
_CERTIFICATE.fields_by_name['content'].message_type = _CERTIFICATESIGNEDDATA
_CERTIFICATE.fields_by_name['signature'].message_type = _CERTIFICATESIGNATURE
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['CertificateSignedData'] = _CERTIFICATESIGNEDDATA
DESCRIPTOR.message_types_by_name['CertificateSignatureData'] = _CERTIFICATESIGNATUREDATA
DESCRIPTOR.message_types_by_name['CertificateSignature'] = _CERTIFICATESIGNATURE
DESCRIPTOR.message_types_by_name['Certificate'] = _CERTIFICATE
DESCRIPTOR.enum_types_by_name['DigestAlgorithm'] = _DIGESTALGORITHM
DESCRIPTOR.enum_types_by_name['SubjectTrustLevel'] = _SUBJECTTRUSTLEVEL

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), dict(
  DESCRIPTOR = _DATE,
  __module__ = 'umesh_cert_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  ))
_sym_db.RegisterMessage(Date)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), dict(
  DESCRIPTOR = _KEY,
  __module__ = 'umesh_cert_pb2'
  # @@protoc_insertion_point(class_scope:Key)
  ))
_sym_db.RegisterMessage(Key)

CertificateSignedData = _reflection.GeneratedProtocolMessageType('CertificateSignedData', (_message.Message,), dict(
  DESCRIPTOR = _CERTIFICATESIGNEDDATA,
  __module__ = 'umesh_cert_pb2'
  # @@protoc_insertion_point(class_scope:CertificateSignedData)
  ))
_sym_db.RegisterMessage(CertificateSignedData)

CertificateSignatureData = _reflection.GeneratedProtocolMessageType('CertificateSignatureData', (_message.Message,), dict(
  DESCRIPTOR = _CERTIFICATESIGNATUREDATA,
  __module__ = 'umesh_cert_pb2'
  # @@protoc_insertion_point(class_scope:CertificateSignatureData)
  ))
_sym_db.RegisterMessage(CertificateSignatureData)

CertificateSignature = _reflection.GeneratedProtocolMessageType('CertificateSignature', (_message.Message,), dict(
  DESCRIPTOR = _CERTIFICATESIGNATURE,
  __module__ = 'umesh_cert_pb2'
  # @@protoc_insertion_point(class_scope:CertificateSignature)
  ))
_sym_db.RegisterMessage(CertificateSignature)

Certificate = _reflection.GeneratedProtocolMessageType('Certificate', (_message.Message,), dict(
  DESCRIPTOR = _CERTIFICATE,
  __module__ = 'umesh_cert_pb2'
  # @@protoc_insertion_point(class_scope:Certificate)
  ))
_sym_db.RegisterMessage(Certificate)


_KEY.fields_by_name['identity'].has_options = True
_KEY.fields_by_name['identity']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))
_KEY.fields_by_name['ed25519_sk'].has_options = True
_KEY.fields_by_name['ed25519_sk']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))
_CERTIFICATESIGNEDDATA.fields_by_name['identity'].has_options = True
_CERTIFICATESIGNEDDATA.fields_by_name['identity']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))
_CERTIFICATESIGNEDDATA.fields_by_name['ed25519_pk'].has_options = True
_CERTIFICATESIGNEDDATA.fields_by_name['ed25519_pk']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))
_CERTIFICATESIGNATURE.fields_by_name['signer_identity'].has_options = True
_CERTIFICATESIGNATURE.fields_by_name['signer_identity']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))
_CERTIFICATESIGNATURE.fields_by_name['subject_identity'].has_options = True
_CERTIFICATESIGNATURE.fields_by_name['subject_identity']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010 '))
_CERTIFICATESIGNATURE.fields_by_name['ed25519_signature'].has_options = True
_CERTIFICATESIGNATURE.fields_by_name['ed25519_signature']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010@'))
# @@protoc_insertion_point(module_scope)
