Import("env")
Import("conf")
Import("objs")

if conf["LIB_WREN"] == "y":

	env.Git('https://github.com/wren-lang/wren/', branch='main')

	objs.append(env.Object([
		File(Glob(env['LIB_DEFAULT_REPO_DIR'] + '/src/vm/*.c"')),
		File(Glob(env['LIB_DEFAULT_REPO_DIR'] + '/src/optional/*.c"')),
	]))
	
	env.Append(CPPPATH = [
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/src/include'),
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/src/optional'),
		Dir(env['LIB_DEFAULT_REPO_DIR'] + '/src/vm'),
	])
